#!/bin/sh

while test `ps auxw | grep mongod | grep -v grep | wc -l` -lt 3
do
        echo `ps auxw | grep mongod | grep -v grep | wc -l`
        echo "Waiting for mongodb..."
        sleep 3
done

echo
echo "-- Configure replica set"

export PRIVATE_IP=`ifconfig | grep 'inet addr' | grep -v '127.0.0.1' | awk '
        match($0, /([0-9]*)\.([0-9]*)\.([0-9]*)\.([0-9]*)/) {
                print substr($0, RSTART, RLENGTH);
        }
'`

RES=`echo "config = {\
      _id: 'rp',\
      members: [\
            {_id: 0, host: '$PRIVATE_IP:27017'},\
            {_id: 1, host: '$PRIVATE_IP:27018'},\
            {_id: 2, host: '$PRIVATE_IP:27019', arbiterOnly: true}\
      ]\
} \n rs.initiate(config)" | mongo --port=27017`

ISSUCCEEDED=`echo ${RES} | grep "\"ok\" : 1" | wc -l`

if test ${ISSUCCEEDED} -eq 0
then
        echo an error occured
        exit 1
fi

while :
do
        sleep 10
done
