#!/bin/sh

export PRIVATE_IP=`ifconfig | grep 'inet addr' | grep -v '127.0.0.1' | awk '
 	match($0, /([0-9]*)\.([0-9]*)\.([0-9]*)\.([0-9]*)/) {
		print substr($0, RSTART, RLENGTH);
	}
'`

echo "config = {\
    _id: 'rp',\
    members: [\
        {_id: 0, host: '$PRIVATE_IP:27017'},\
        {_id: 1, host: '$PRIVATE_IP:27018'},\
        {_id: 2, host: '$PRIVATE_IP:27019', arbiterOnly: true}\
    ]\
} \n rs.initiate(config)" | mongo --port=27017
