#!/bin/sh
# primary & secondary
mongod --dbpath=/data/node1 --replSet=rp --port=27017 --fork --logpath /var/log/mongodb27017.log --logappend
mongod --dbpath=/data/node2 --replSet=rp --port=27018 --fork --logpath /var/log/mongodb27018.log --logappend
# arbiter
mongod --dbpath=/data/node3 --replSet=rp --port=27019 --fork --logpath /var/log/mongodb27019.log --logappend

# configure replication
export PRIVATE_IP=`ifconfig | grep 'inet addr' | grep -v '127.0.0.1' | awk '
 	match($0, /([0-9]*)\.([0-9]*)\.([0-9]*)\.([0-9]*)/) {
		print substr($0, RSTART, RLENGTH);
	}
'`

echo "config = {\
    _id: 'rp',\
    members: [\
        {_id: 0, host: '$PRIVATE_IP:27017'},\
        {_id: 1, host: '$PRIVATE_IP:27018'},\
        {_id: 2, host: '$PRIVATE_IP:27019', arbiterOnly: true}\
    ]\
} \n rs.initiate(config)" | mongo --port=27017

while :
do
        sleep 5
done
